---
abstract: 'Handle passing multiple types of messages between screens of a web application using session or stash.'
author:
  - 'Geovanny Junio <geovannyjs@gmail.com>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::Test: 0
  Moose: 0
  Test::More: 0
  lib: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-SimpleMessage
requires:
  strictures: 1
version: 0.0.2
